name: Build Dashboard (diário)

on:
  schedule:
    - cron: '0 11 * * *'  # 07:00 America/Campo_Grande ≈ 11:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pytz

      - name: Build
        run: |
          python build/build.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json docs/index.html
          git commit -m "build: atualização diária do dashboard" || echo "nada a commitar"
          git push
